# Generated by Django 5.1.2 on 2024-11-11 16:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Concept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('normalized_name', models.CharField(editable=False, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('last_studied', models.DateTimeField(blank=True, null=True)),
                ('concepts', models.ManyToManyField(blank=True, related_name='topics', to='topics.concept')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('answers', models.JSONField(help_text='Store answers as a JSON array')),
                ('correct', models.CharField(help_text='Text of the correct answer', max_length=100)),
                ('correct_count', models.PositiveIntegerField(default=0, help_text='Number of times the user has correctly answered this question')),
                ('wrong_count', models.PositiveIntegerField(default=0, help_text='Number of times user answered this question wrongly')),
                ('skip_count', models.PositiveIntegerField(default=0, help_text='Number of times the skipped this question')),
                ('last_asked', models.DateTimeField(blank=True, help_text='The last time this question was answered', null=True)),
                ('concepts', models.ManyToManyField(blank=True, related_name='questions', to='topics.concept')),
                ('main_concept', models.ForeignKey(blank=True, help_text='The main concept on which this question was generated', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_concept_questions', to='topics.concept')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='topics.topic')),
            ],
        ),
    ]
