# Generated by Django 5.1.2 on 2024-11-24 20:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('topics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chunk',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='topics.document'),
        ),
        migrations.AddField(
            model_name='question',
            name='concepts',
            field=models.ManyToManyField(blank=True, related_name='questions', to='topics.concept'),
        ),
        migrations.AddField(
            model_name='question',
            name='main_concept',
            field=models.ForeignKey(blank=True, help_text='The main concept on which this question was generated', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_concept_questions', to='topics.concept'),
        ),
        migrations.AddField(
            model_name='explanation',
            name='question',
            field=models.OneToOneField(help_text='The question that this explanation is linked to.', on_delete=django.db.models.deletion.CASCADE, related_name='explanation', to='topics.question'),
        ),
        migrations.AddField(
            model_name='topic',
            name='concepts',
            field=models.ManyToManyField(blank=True, related_name='topics', to='topics.concept'),
        ),
        migrations.AddField(
            model_name='topic',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='topics.topic'),
        ),
        migrations.AddField(
            model_name='userknowledge',
            name='concept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_records', to='topics.concept'),
        ),
        migrations.AddField(
            model_name='userknowledge',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_records', to='topics.topic'),
        ),
        migrations.AddField(
            model_name='userknowledge',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='document',
            unique_together={('name', 'user')},
        ),
        migrations.AddConstraint(
            model_name='userknowledge',
            constraint=models.UniqueConstraint(fields=('user', 'topic', 'concept'), name='unique_user_topic_concept'),
        ),
    ]
