# Generated by Django 5.1.2 on 2024-11-22 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='topic_data',
            field=models.JSONField(default=dict, help_text='Store custom settings like question type and source frequencies as JSON.'),
        ),
    ]
