# Generated by Django 5.1.2 on 2024-11-09 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0002_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='correct_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of times the user has correctly answered this question'),
        ),
        migrations.AddField(
            model_name='question',
            name='skip_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of times the skipped this question'),
        ),
        migrations.AddField(
            model_name='question',
            name='wrong_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of times user answered this question wrongly'),
        ),
    ]
