# Generated by Django 5.1.2 on 2024-11-09 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0003_question_correct_count_question_skip_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='last_asked',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
