# Generated by Django 5.1.2 on 2024-11-09 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0004_question_last_asked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='last_asked',
            field=models.DateTimeField(blank=True, help_text='The last time this question was answered', null=True),
        ),
    ]
