# Generated by Django 5.1.2 on 2024-11-10 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0005_alter_question_last_asked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='correct',
            field=models.CharField(help_text='Text of the correct answer', max_length=100),
        ),
    ]
